src/Web/Controllers/BranchController.cs
using HotelBooking.Core.Dtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace HotelBooking.Web.Controllers
{
    public class BranchController : Controller
    {
        //Hosted web API REST Service base url
        string baseUri = "https://localhost:44391/api/";
        HttpClient client = new HttpClient();

        public async Task<IActionResult> Index()
        {
            IEnumerable<BranchDto> branchsView = null;

            //Passing service base url
            client.BaseAddress = new Uri(baseUri);
            client.DefaultRequestHeaders.Clear();
            //Define request data format
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            //Sending request to find web api REST service resource GetAllBranchs using HttpClient
            HttpResponseMessage res = await client.GetAsync("Branch/GetAllBranchs");
            //Checking the response is successful or not which is sent using HttpClient
            if (res.IsSuccessStatusCode)
            {
                //Storing the response details recieved from web api
                string branchRes = await res.Content.ReadAsStringAsync();
                //Deserializing the response recieved from web api and storing into the Branchs IEnumerable
                branchsView = JsonConvert.DeserializeObject<IEnumerable<BranchDto>>(branchRes);

                return View(branchsView);
            }
            else
            {
                return View(branchsView = null);
            }

        }
        public async Task<IActionResult> Branch(int id)
        {
            IEnumerable<RoomDto> branchRoomView = null;

            client.BaseAddress = new Uri(baseUri);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("applicaion/json"));

            HttpResponseMessage res = await client.GetAsync($"Room/GetRoomsByBranchId?branchId={id}");

            if (res.IsSuccessStatusCode)
            {
                string branchRes = await res.Content.ReadAsStringAsync();
                branchRoomView = JsonConvert.DeserializeObject<IEnumerable<RoomDto>>(branchRes);

                return View(branchRoomView);
            }
            else
            {
                return View();
            }
        }
    }
}

src/Web/Controllers/ReservationController.cs
using HotelBooking.Core.Dtos;
using HotelBooking.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace HotelBooking.Web.Controllers
{
    public class ReservationController : Controller
    {
        string baseUrl = "https://localhost:44391/api/";
        HttpClient client = new HttpClient();

        public IActionResult CreateReservation()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateReservation(ReservationDto reserv)
        {
            
            client.BaseAddress = new Uri(baseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage res = await client.PostAsJsonAsync<ReservationDto>("Reservation/CreateReservationWithRooms", reserv);

            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");

            }
            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

            return View(reserv);
        }
    }
}

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/site/css/bootstrap.css">
    <link rel="stylesheet" href="~/site/vendors/linericon/style.css">
    <link rel="stylesheet" href="~/site/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/site/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/site/vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="~/site/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="~/site/vendors/owl-carousel/owl.carousel.min.css">
    <!-- main css -->
    <link rel="stylesheet" href="~/site/css/style.css">
    <link rel="stylesheet" href="~/site/css/responsive.css">
</head>
<body>
    <!--================Header Area =================-->
    <header class="header_area">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" asp-controller="Home" asp-action="Index"><img src="~/site/image/Logo.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Branch" asp-action="Index">Branchs</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Reservation" asp-action="CreateReservation">Reservation</a></li>

                        <li class="nav-item"><a class="nav-link" href="about.html">About us</a></li>

                        <li class="nav-item"><a class="nav-link" href="accomodation.html">Accomodation</a></li>

                        <li class="nav-item"><a class="nav-link" href="gallery.html">Gallery</a></li>

                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                <li class="nav-item"><a class="nav-link" href="blog-single.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="elements.html">Elemests</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    </ul>
                    <div class="ml-2">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!--================Header Area =================-->
   
            @RenderBody()
  
    <!--================ start footer Area  =================-->
    <footer class="footer-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6 class="footer_title">About Agency</h6>
                        <p>The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6 class="footer_title">Navigation Links</h6>
                        <div class="row">
                            <div class="col-4">
                                <ul class="list_style">
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Feature</a></li>
                                    <li><a href="#">Services</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col-4">
                                <ul class="list_style">
                                    <li><a href="#">Team</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6 class="footer_title">Newsletter</h6>
                        <p>For business professionals caught between high OEM price and mediocre print and graphic output, </p>
                        <div id="mc_embed_signup">
                            <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                <div class="input-group d-flex flex-row">
                                    <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn sub-btn"><span class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget instafeed">
                        <h6 class="footer_title">InstaFeed</h6>
                        <ul class="list_style instafeed d-flex flex-wrap">
                            <li><img src="~/site/image/instagram/Image-01.jpg" alt=""></li>
                            <li><img src="~/site/image/instagram/Image-02.jpg" alt=""></li>
                            <li><img src="~/site/image/instagram/Image-03.jpg" alt=""></li>
                            <li><img src="~/site/image/instagram/Image-04.jpg" alt=""></li>
                            @*<li><img src="~/site/image/instagram/Image-05.jpg" alt=""></li>
                            <li><img src="~/site/image/instagram/Image-06.jpg" alt=""></li>
                            <li><img src="~/site/image/instagram/Image-07.jpg" alt=""></li>
                            <li><img src="~/site/image/instagram/Image-08.jpg" alt=""></li>*@
                        </ul>
                    </div>
                </div>
            </div>
            <div class="border_line"></div>
            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved<i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">Morad Safwat</a>
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!--================ End footer Area  =================-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/site/js/jquery-3.2.1.min.js"></script>
    <script src="~/site/js/popper.js"></script>
    <script src="~/site/js/bootstrap.min.js"></script>
    <script src="~/site/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/site/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/site/js/mail-script.js"></script>
    <script src="~/site/vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.js"></script>
    <script src="~/site/vendors/nice-select/js/jquery.nice-select.js"></script>
    <script src="~/site/js/mail-script.js"></script>
    <script src="~/site/js/stellar.js"></script>
    <script src="~/site/vendors/lightbox/simpleLightbox.min.js"></script>
    <script src="~/site/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>